# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: nsq-cluster 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "nsq-cluster"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Brendan Schwartz"]
  s.date = "2014-04-14"
  s.description = "Setup nsqd, nsqlookupd, and nsqadmin in a jiffy. Great for testing!"
  s.email = "brendan@wistia.com"
  s.executables = ["nsq-cluster"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    ".ruby-gemset",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/nsq-cluster",
    "lib/nsq-cluster.rb",
    "lib/nsq-cluster/nsqadmin.rb",
    "lib/nsq-cluster/nsqd.rb",
    "lib/nsq-cluster/nsqlookupd.rb",
    "lib/nsq-cluster/process_wrapper.rb",
    "nsq-cluster.gemspec",
    "test/helper.rb",
    "test/nsq_cluster_spec.rb"
  ]
  s.homepage = "http://github.com/wistia/nsq-cluster"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Easily setup and manage a local NSQ cluster"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nsq-cluster>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<nsq-cluster>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<nsq-cluster>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

